name: Release

on:
  push:
    tags:
    - '*'   

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Download Wallet
        run: |
          mkdir -p ${{ github.workspace }}/download
          curl -k https://quantumcrafters.org/download/QuantumSwapWallet-1.2.2-arm64.dmg --output ${{ github.workspace }}\download\QuantumSwapWallet-1.2.2-arm64.dmg 
          curl -k https://quantumcrafters.org/download/QuantumSwapWallet-1.2.2-x64.dmg --output ${{ github.workspace }}\download\QuantumSwapWallet-1.2.2-x64.dmg 
      - name: Create Release
        run: |
          powershell Get-FileHash ${{ github.workspace }}\download\QuantumSwapWallet-1.2.2-arm64.dmg > ${{ github.workspace }}\download\QuantumSwapWallet-1.2.2-arm64.dmg.txt
          powershell Get-FileHash ${{ github.workspace }}\download\QuantumSwapWallet-1.2.2-x64.dmg > ${{ github.workspace }}\download\QuantumSwapWallet-1.2.2-x64.dmg.txt         
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: qc-release-windows
          path: |
              ${{ github.workspace }}/download/*.*
              
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "download/*.*"
